name: Build and Deploy Microservices

on:
  push:
    branches:
      - feature/project-setup

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "553336999743"
  ECS_CLUSTER: spoke-ecs-cluster

jobs:
  build-and-deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC token claims
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        run: |
          TOKEN=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value')

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2 | tr '_-' '/+' | base64 -d 2>/dev/null)

          echo "$PAYLOAD" | jq '{
            sub,
            aud,
            repository,
            repository_id,
            repository_owner,
            repository_owner_id,
            ref
          }'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::553336999743:role/github-actions-ecs-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build API image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-api:latest \
            ./api

      - name: Build UI image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-ui:latest \
            ./ui

      - name: Push API image
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-api:latest

      - name: Push UI image
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/user-ui:latest

      - name: Deploy API to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service user-api-service \
            --force-new-deployment

      - name: Deploy UI to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service user-ui-service \
            --force-new-deployment

      - name: Wait for ECS services
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services user-api-service user-ui-service

      - name: Deployment summary
        run: |
          echo "Deployment completed successfully"
          echo "Commit: $GITHUB_SHA"
          echo "ECS Cluster: $ECS_CLUSTER"